// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@/components/navbar/navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Jobs = ({ children }: any) => {
  return (
    <>
      <div className="">
        <Navbar />
        <div className="h-full w-full ">{children}</div>
      </div>
    </>
  );
};

export default Jobs;
